---
driver:
  name: docker
  hostname: heat.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: <%=ENV['SALT_VERSION'] || 'latest'%>
  require_chef: false
  log_level: error
  formula: heat
  grains:
    noservices: True
  dependencies:
    - name: keystone
      repo: git
      source: https://github.com/salt-formulas/salt-formula-keystone
  state_top:
    base:
      "*":
        - heat
  pillars:
    top.sls:
      base:
        "*":
          - heat

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: server_cluster
    provisioner:
      pillars-from-files:
        heat.sls: tests/pillar/server_cluster.sls

  - name: server_plugin_dirs
    provisioner:
      pillars-from-files:
        heat.sls: tests/pillar/server_plugin_dirs.sls

  - name: server_single
    provisioner:
      pillars-from-files:
        heat.sls: tests/pillar/server_single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
